#page title
page_title: Baby Wize # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 718043190 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: uk # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
app_icon: assets/Baby Wize-with BG.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: BabyWize # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: FREE # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: A quick, lightweight, accessible baby tracking app!

enable_smart_app_banner: false # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Noam Efergan
your_link:
your_city: Manchester
email_address: efergann@gmail.com
facebook_username:
instagram_username:
twitter_username: No_Wham
github_username: NoamEfergan
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Lightweight!
    description: Quick to load, quick to use, spend less time on the app and more time with your child!
    fontawesome_icon_name: bolt

  - title: Customisable
    description: Ml? oz? you decide!
    fontawesome_icon_name: globe

  - title: Don't want to create an account? You don't have to!
    description: Use the full extent of the app without ever creating an account ( your data will not be persisted between devices)
    fontawesome_icon_name: user-shield

  - title: Fully accessible!
    description: Any font size, from smallest to largest, is fully supported in the app!
    fontawesome_icon_name: people-group

  - title: Made with love, by a parent - for parents
    description: Here to be the helping hand that you might need
    fontawesome_icon_name: heart

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
